/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface ExportConnectivityDiagram {
    'connectedAreas': any;
    'downloadPng': () => Promise<void>;
    'el': any;
    'getCSVData': () => Promise<unknown>;
    'theme': string;
  }
  interface HbpConnectivityMatrixRow {
    'datasetUrl': string;
    'loadurl': string;
    'region': string;
    'showDatasetName': string;
    'showDescription': string;
    'showExport': string;
    'showSource': string;
    'showTitle': string;
    'showToolbar': string;
    'theme': string;
  }
}

declare global {


  interface HTMLExportConnectivityDiagramElement extends Components.ExportConnectivityDiagram, HTMLStencilElement {}
  var HTMLExportConnectivityDiagramElement: {
    prototype: HTMLExportConnectivityDiagramElement;
    new (): HTMLExportConnectivityDiagramElement;
  };

  interface HTMLHbpConnectivityMatrixRowElement extends Components.HbpConnectivityMatrixRow, HTMLStencilElement {}
  var HTMLHbpConnectivityMatrixRowElement: {
    prototype: HTMLHbpConnectivityMatrixRowElement;
    new (): HTMLHbpConnectivityMatrixRowElement;
  };
  interface HTMLElementTagNameMap {
    'export-connectivity-diagram': HTMLExportConnectivityDiagramElement;
    'hbp-connectivity-matrix-row': HTMLHbpConnectivityMatrixRowElement;
  }
}

declare namespace LocalJSX {
  interface ExportConnectivityDiagram {
    'connectedAreas'?: any;
    'el'?: any;
    'theme'?: string;
  }
  interface HbpConnectivityMatrixRow {
    'datasetUrl'?: string;
    'loadurl'?: string;
    'onCollapsedMenuChanged'?: (event: CustomEvent<any>) => void;
    'onConnectivityDataReceived'?: (event: CustomEvent<any>) => void;
    'region'?: string;
    'showDatasetName'?: string;
    'showDescription'?: string;
    'showExport'?: string;
    'showSource'?: string;
    'showTitle'?: string;
    'showToolbar'?: string;
    'theme'?: string;
  }

  interface IntrinsicElements {
    'export-connectivity-diagram': ExportConnectivityDiagram;
    'hbp-connectivity-matrix-row': HbpConnectivityMatrixRow;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'export-connectivity-diagram': LocalJSX.ExportConnectivityDiagram & JSXBase.HTMLAttributes<HTMLExportConnectivityDiagramElement>;
      'hbp-connectivity-matrix-row': LocalJSX.HbpConnectivityMatrixRow & JSXBase.HTMLAttributes<HTMLHbpConnectivityMatrixRowElement>;
    }
  }
}


