/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { CustomTool } from "./components/hbp-connectivity-matrix-row/hbp-connectivity-matrix-row";
export namespace Components {
    interface ExportConnectivityDiagram {
        "connectedAreas": any;
        "datasetInfo": any;
        "downloadCSV": () => Promise<void>;
        "downloadPng": () => Promise<void>;
        "el": any;
        "getCSVData": () => Promise<unknown>;
        "hideView": string;
        "theme": string;
    }
    interface FullConnectivityGrid {
        "gridheight": string;
        "gridwidth": string;
        "pixelsize": string;
        "textwidth": string;
        "theme": string;
    }
    interface HbpConnectivityMatrixRow {
        "_tools_custom": CustomTool[];
        "customDatasetSelector": string;
        "customHeight": string;
        "customWidth": string;
        "datasetUrl": string;
        "downloadCSV": () => Promise<void>;
        "hideExportView": string;
        "loadurl": string;
        "region": string;
        "showDatasetName": string;
        "showDescription": string;
        "showExport": string;
        "showSource": string;
        "showTitle": string;
        "showToolbar": string;
        "theme": string;
        "tools_custom": CustomTool[] | string;
        "tools_showallresults": string;
        "tools_showlog": string;
    }
}
declare global {
    interface HTMLExportConnectivityDiagramElement extends Components.ExportConnectivityDiagram, HTMLStencilElement {
    }
    var HTMLExportConnectivityDiagramElement: {
        prototype: HTMLExportConnectivityDiagramElement;
        new (): HTMLExportConnectivityDiagramElement;
    };
    interface HTMLFullConnectivityGridElement extends Components.FullConnectivityGrid, HTMLStencilElement {
    }
    var HTMLFullConnectivityGridElement: {
        prototype: HTMLFullConnectivityGridElement;
        new (): HTMLFullConnectivityGridElement;
    };
    interface HTMLHbpConnectivityMatrixRowElement extends Components.HbpConnectivityMatrixRow, HTMLStencilElement {
    }
    var HTMLHbpConnectivityMatrixRowElement: {
        prototype: HTMLHbpConnectivityMatrixRowElement;
        new (): HTMLHbpConnectivityMatrixRowElement;
    };
    interface HTMLElementTagNameMap {
        "export-connectivity-diagram": HTMLExportConnectivityDiagramElement;
        "full-connectivity-grid": HTMLFullConnectivityGridElement;
        "hbp-connectivity-matrix-row": HTMLHbpConnectivityMatrixRowElement;
    }
}
declare namespace LocalJSX {
    interface ExportConnectivityDiagram {
        "connectedAreas"?: any;
        "datasetInfo"?: any;
        "el"?: any;
        "hideView"?: string;
        "theme"?: string;
    }
    interface FullConnectivityGrid {
        "gridheight"?: string;
        "gridwidth"?: string;
        "onConnectivityDataReceived"?: (event: CustomEvent<any>) => void;
        "pixelsize"?: string;
        "textwidth"?: string;
        "theme"?: string;
    }
    interface HbpConnectivityMatrixRow {
        "_tools_custom"?: CustomTool[];
        "customDatasetSelector"?: string;
        "customHeight"?: string;
        "customWidth"?: string;
        "datasetUrl"?: string;
        "hideExportView"?: string;
        "loadurl"?: string;
        "onCollapsedMenuChanged"?: (event: CustomEvent<any>) => void;
        "onConnectivityDataReceived"?: (event: CustomEvent<any>) => void;
        "onCustomToolEvent"?: (event: CustomEvent<any>) => void;
        "onDatasetDataReceived"?: (event: CustomEvent<any>) => void;
        "region"?: string;
        "showDatasetName"?: string;
        "showDescription"?: string;
        "showExport"?: string;
        "showSource"?: string;
        "showTitle"?: string;
        "showToolbar"?: string;
        "theme"?: string;
        "tools_custom"?: CustomTool[] | string;
        "tools_showallresults"?: string;
        "tools_showlog"?: string;
    }
    interface IntrinsicElements {
        "export-connectivity-diagram": ExportConnectivityDiagram;
        "full-connectivity-grid": FullConnectivityGrid;
        "hbp-connectivity-matrix-row": HbpConnectivityMatrixRow;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "export-connectivity-diagram": LocalJSX.ExportConnectivityDiagram & JSXBase.HTMLAttributes<HTMLExportConnectivityDiagramElement>;
            "full-connectivity-grid": LocalJSX.FullConnectivityGrid & JSXBase.HTMLAttributes<HTMLFullConnectivityGridElement>;
            "hbp-connectivity-matrix-row": LocalJSX.HbpConnectivityMatrixRow & JSXBase.HTMLAttributes<HTMLHbpConnectivityMatrixRowElement>;
        }
    }
}
